import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { use, useState } from 'react'

export default function Home() {

  var [email, setEmail] = useState()

  var [submitted, setSubmitted] = useState(false)

  async function updateTable() {
    setSubmitted(true)
  }

  return (
		<>
			<Head>
				<title>Landing Page</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className={styles.head}>
					<img className={styles.logoImg} src={'/logo.png'} />
					<h1>Website Coming Soon!</h1>
					<p>Thank you shopping with us!</p>
					{!submitted ? (
						<>
							<p>Claim Your Free E-Book Now by Entrering Your Email Below</p>

							<form className={styles.signUpForm} name={'emailCapture'} method={'POST'} data-netlify='true'>
								<input type='hidden' name='form-name' value='emailCapture' />
								<input type={'email'} name={'email'} onChange={(e) => setEmail(e.target.value)} />
								<p hidden>
									<label>
										Don&apos;t fill this out: <input name='bot-field' />
									</label>
								</p>
								<button type='button' onClick={updateTable}>
									Claim
								</button>
							</form>
						</>
					) : (
						<div>
							<h3 style={{ marginTop: '2rem', marginBottom: '2rem' }}>Thanks! Click the button below to download your free E-Book.</h3>
							<a className={styles.downloadBtn} href='/coffee_collection.pdf' download>
								Download FREE E-Book
							</a>
						</div>
					)}
				</div>
			</main>
		</>
	)
}
