import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react'
import pool from 'config/db'

export default function Home() {

  var [email, setEmail] = useState()

  async function updateTable() {
    
  }

  return (
		<>
			<Head>
				<title>Landing Page</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className={styles.head}>
					<img className={styles.logoImg} src={'/logo.png'} />
          <h1>Website Coming Soon!</h1>
          <p>Thank you shopping with us!</p>
          <p>Claim Your Free E-Book Now by Entrering Your Email Below</p>

          <form className={styles.signUpForm}>
            <input type={'email'} onChange={(e) => setEmail(e.target.value)} />
            <button type='submit' onClick={updateTable}>Claim</button>
          </form>
				</div>
			</main>
		</>
	)
}
