import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {
	return (
		<>
			<Head>
				<title>Landing Page</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className={styles.head}>
					<img className={styles.logoImg} src={'/logo.png'} />
					<h1>Website Coming Soon!</h1>
					<p>Thank you shopping with us!</p>
					<div>
						<h3 style={{ marginTop: '2rem', marginBottom: '2rem' }}>Thanks! Click the button below to download your free E-Book.</h3>
						<a className={styles.downloadBtn} href='/coffee_collection.pdf' download>
							Download FREE E-Book
						</a>
					</div>
				</div>
			</main>
		</>
	)
}
